# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_asset_durationms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
